apiVersion: apps/v1
kind: Deployment
metadata:
  name: xl-release-deployment
  namespace: xl-release
  labels:
    app: xl-release 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: xl-release 
  template:
    metadata:
      labels:
        app: xl-release 
    spec:
      containers:
        - name: xl-release
          image: xebialabs/xl-release
          env:
            - name: ADMIN_PASSWORD
              value: "papagaio"
            - name: ACCEPT_EULA
              value: "Y"
          ports:
          - containerPort: 5516
      nodeSelector:
        disktype: ssd8    