apiVersion: apps/v1
kind: Deployment
metadata:
  name: xlrelease-deployment
  namespace: xl-release
  labels:
    app: xlrelease 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: xlrelease 
  template:
    metadata:
      labels:
        app: xlrelease 
    spec:
      containers:
        - name: xlrelease
          image: xebialabs/xl-release
          env:
            - name: ADMIN_PASSWORD
              value: "papagaio"
            - name: ACCEPT_EULA
              value: "Y"
          ports:
          - containerPort: 80