apiVersion: v1
kind: Service
metadata:
  name: svc-site-nginx-lb
  namespace: site
spec:
  selector:
    app: site-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer