version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"   # Porta para o receptor OTLP via gRPC
      - "55681:55681" # Porta para o receptor OTLP via HTTP

  jaeger:
    image: jaegertracing/all-in-one:1.43
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"  # UI do Jaeger
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"    # Exportador Zipkin
      
