receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
  zipkin:
    endpoint: "http://jaeger:9411/api/v2/spans"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin]
