apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-client
  namespace: kafka
spec:
  containers:
    - name: kafka-test-client
      image: bitnami/kafka:latest
      command:
        - sleep
        - "3600"
      env:
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
  restartPolicy: Never
